name: 'Publish Teams Webhook Notification'
description: 'Publish Teams Webhook Notification'
inputs:
  teamsWebhookUrl:
    description: 'Teams Webhook Url'
    required: true
  mentions:
    description: 'Mentions'
    required: true
  title:
    description: 'Message Title'
    required: true
  workflowName:
    description: 'Workflow Name'
    required: true
  buildId:
    description: 'Build Id'
    required: true
  githubRepo:
    description: 'Github Repository'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Commerce Bundle Modules
      if: ${{ inputs.installModules  == 'true' }}
      working-directory: ${{ github.action_path }}
      env: 
        INSTALL_FOLDER: 'modules'
      shell: pwsh
      run: |
        Write-Output "Teams Webhook Url: ${{ inputs.teamsWebhookUrl }}"
        Write-Output "Mentions: ${{ inputs.mentions }}"
        Write-Output "Title: ${{ inputs.title }}"
        Write-Output "Workflow Name: ${{ inputs.workflowName }}"
        Write-Output "Build Id: ${{ inputs.buildId }}"
        Write-Output "Github Repo: ${{ inputs.githubRepo }}"
        Write-Output "Command: ./scripts/post-teams-notification.ps1 -teamsWebhookUrl ${{ inputs.teamsWebhookUrl }} -mentions ${{ inputs.mentions }} -title ${{ inputs.title }} -workflowName ${{ inputs.workflowName }} -buildId ${{ inputs.buildId }} -githubRepo ${{ inputs.githubRepo }}"
        
        ./scripts/post-teams-notification.ps1 -teamsWebhookUrl ${{ inputs.teamsWebhookUrl }} -mentions ${{ inputs.mentions }} -title ${{ inputs.title }} -workflowName ${{ inputs.workflowName }} -buildId ${{ inputs.buildId }} -githubRepo ${{ inputs.githubRepo }}