name: 'changelog-generator'
description: 'Generates changelog'
inputs:
    releases_list:
      description: 'List of Github Releases'
      required: true
outputs:
  changelog:
    description: 'Result'
runs:
  using: 'node12'
  main: 'index.js'