name: 'update-webhook-configuration'
description: 'Updates a webhook configured in a repository.'
inputs:
  githubToken:
    description: "GitHub token"
    required: false
  repoOwner:
    description: "The account owner of the repository."
    required: false
    default: "VirtoCommerce"
  repoName:
    description: "The name of the repository."
    required: false
  webhookUrl:
    description: "The URL to which the payloads will be delivered."
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js' 