name: "Deploy Github Actions"
description: "Deploy a common Github Action to a repo."
inputs:
  GITHUB_TOKEN:
    description: "Github secret token to allow automated publishing of artifacts to a release."
    required: true
  USER:
    default:  "VirtoCommerce"
    description: "Organization or username."
    required: false
  REPOSITORY:
    description: "Name of the repository."
    required: true
  TARGET_BRANCH:
    default: "dev"
    description: "Typically the develop or integration branch."
    required: false
  GHA_DEPLOYMENT_FOLDER:
    default: ""
    description: "Folder name where the to-be-deployed Github Actions reside."
    required: false
  COMMIT_MESSAGE:
    default: "Updating Github Action workflows."
    description: "Custom message for commit. Default message: Updating Github Action workflows."
    required: false
  GHA_DEPLOY_BRANCH_NAME:
    default: "update_gha_source"
    description: "Name of the branch to be created. Default branch name: update_gha_source."
    required: false
runs:
  using: "docker"
  image: "Dockerfile"