name: 'build-docker-image'
description: 'Build docker image'
inputs:
  outputs:
    description: "Output destination"
    default: ''
    required: false
  imageName: 
    description: "Name of Docker Image"
    required: true
  tag:
    description: "Tag of Docker Image"
    required: true
  dockerFiles:
    description: "Files urls for build docker image"
    required: true

outputs:
  imageName: 
    description: "Name of Docker Image"
runs:
  using: 'node12'
  main: 'dist/index.js'