name: 'Deploy Versioned Documentation'
description: 'Deploy versioned documentation using mike based on version-config.json'
inputs:
  azureSubscriptionId:
    description: "Azure Subscription ID"
    required: true
  azureResourceGroupName:
    description: "Azure Resource Group Name"
    required: true
  azureWebAppName:
    description: "Azure WebApp Name"
    required: true
  azureTenantId:
    description: ""
    required: true
  azureApiKey:
    description: ""
    required: true
  azureAppId:
    description: ""
    required: true
  dockerRegistry:
    description: "Docker Registry"
    required: true
  dockerUsr:
    description: "Docker User"
    required: true
  dockerPwd:
    description: "Docker Password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Clone vc-docs repository
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        # Always clone fresh to ensure clean state
        if [ -d "vc-docs" ]; then
          echo "⚠️ Removing existing vc-docs directory"
          rm -rf vc-docs
        fi
        echo "📦 Cloning vc-docs repository (feature/structure_redesign branch)..."
        git clone https://github.com/VirtoCommerce/vc-docs --branch "feature/structure_redesign"
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Use specific version for better compatibility

    - name: Install dependencies
      shell: bash
      run: |
        # Dependencies might already be installed from workflow, but ensure they are present
        echo "📦 Checking/Installing dependencies..."
        
        # Check if dependencies already installed
        if ! command -v mkdocs &> /dev/null; then
          # Install MkDocs and core dependencies
          pip install mkdocs-material==9.5.4
          pip install mike
          
          # Install all required MkDocs plugins
          pip install mkdocs-monorepo-plugin
          pip install mkdocs-awesome-pages-plugin
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-minify-plugin
          pip install mkdocs-redirects
          pip install mkdocs-include-markdown-plugin
        else
          echo "✅ Dependencies already installed"
        fi
        
        # Try to install from requirements.txt if exists
        if [ -f "vc-docs/requirements.txt" ]; then
          pip install -r vc-docs/requirements.txt
        elif [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
        fi
        
        # Install jq for JSON parsing if not present
        if ! command -v jq &> /dev/null; then
          sudo apt-get update && sudo apt-get install -y jq
        fi

    - name: Configure Git for mike
      shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Build documentation using build.ps1
      shell: pwsh
      working-directory: ${{ github.workspace }}/vc-docs
      run: |
        # Ensure all dependencies are available for build.ps1
        Write-Host "📦 Building documentation..."
        
        # Run the existing build script
        ./build.ps1
        
        if ($LASTEXITCODE -ne 0) {
          Write-Host "❌ Build failed with exit code: $LASTEXITCODE"
          Write-Host "Checking Python dependencies..."
          pip list | Select-String "mkdocs"
          exit $LASTEXITCODE
        }

    - name: Download existing gh-pages (if exists)
      shell: bash
      working-directory: ${{ github.workspace }}/vc-docs
      run: |
        # Try to fetch existing gh-pages branch to preserve old versions
        git fetch origin gh-pages:gh-pages || echo "No existing gh-pages branch"

    - name: Check deployment configuration
      id: check-version
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        if ./check-version-update.sh; then
          echo "should_deploy=true" >> $GITHUB_OUTPUT
          # Export version info for next steps
          VERSION=$(jq -r '.version' version-config.json)
          ALIAS=$(jq -r '.alias' version-config.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "alias=$ALIAS" >> $GITHUB_OUTPUT
        else
          echo "should_deploy=false" >> $GITHUB_OUTPUT
        fi

    - name: Deploy versioned documentation
      if: steps.check-version.outputs.should_deploy == 'true'
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        echo "🚀 Deploying from configuration file..."
        # Check if it's a new version or update to existing
        if [ -f ".last-deployed-version" ]; then
          LAST_VERSION=$(cat ".last-deployed-version")
          CURRENT_VERSION=$(jq -r '.version' version-config.json)
          if [ "$CURRENT_VERSION" = "$LAST_VERSION" ]; then
            ./deploy-from-config.sh --push --update-existing
          else
            ./deploy-from-config.sh --push
          fi
        else
          ./deploy-from-config.sh --push
        fi

    - name: List deployed versions
      if: steps.check-version.outputs.should_deploy == 'true'
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        echo "📚 Currently deployed versions:"
        mike list

    - name: Prepare versioned content for Docker build
      if: steps.check-version.outputs.should_deploy == 'true'
      shell: bash
      run: |
        # Clone the gh-pages branch content (versioned docs from mike)
        git clone --single-branch --branch gh-pages https://github.com/${{ github.repository }}.git gh-pages-content

        # Replace vc-docs/site with versioned content from mike
        rm -rf vc-docs/site
        mkdir -p vc-docs/site
        cp -r gh-pages-content/* vc-docs/site/

        echo "✅ Replaced site content with versioned documentation from mike"
        echo "📁 Content structure:"
        ls -la vc-docs/site/

    - name: Build and Push Docker Image
      if: steps.check-version.outputs.should_deploy == 'true'
      shell: pwsh
      working-directory: ${{ github.workspace }}
      run: |
        dotnet tool install --global VirtoCommerce.GlobalTool

        # Get version from config for Docker tag
        cd vc-docs
        $VERSION = (Get-Content version-config.json | ConvertFrom-Json).version
        cd ..

        # Copy your existing Docker files (assuming they're in your action path)
        Copy-Item -Path ${{ github.action_path }}/docker/* -Destination ./ -Recurse -Force

        # Build and push with versioned tag
        vc-build BuildAndPush -DockerUsername ${{ inputs.dockerUsr }} -DockerPassword ${{ inputs.dockerPwd }} -DockerfilePath ./Dockerfile -DockerImageName ${{ inputs.dockerRegistry }}/vcpt/docs -DockerImageTag "$VERSION-$env:GITHUB_RUN_NUMBER" -DockerRegistryUrl ${{ inputs.dockerRegistry }}

        echo "✅ Built and pushed Docker image: ${{ inputs.dockerRegistry }}/vcpt/docs:$VERSION-$env:GITHUB_RUN_NUMBER"

    # - name: Deploy to Azure Web App
    #   if: steps.check-version.outputs.should_deploy == 'true'
    #   shell: bash
    #   env:
    #     AzureSubscriptionIDProd: ${{ inputs.azureSubscriptionId }}
    #     AzureResourceGroupNameProd: ${{ inputs.azureResourceGroupName }}
    #     AzureWebAppNameProd: ${{ inputs.azureWebAppName }}
    #     AzureAPIKey: ${{ inputs.azureApiKey }}
    #     AzureTenantID: ${{ inputs.azureTenantId }}
    #     AzureAppID: ${{ inputs.azureAppId }}
    #   run: |
    #     # Get version from config
    #     cd vc-docs
    #     VERSION=$(jq -r '.version' version-config.json)
    #     DockerImageName="${{ inputs.dockerRegistry }}/vcpt/docs:${VERSION}-${{ github.run_number }}"

    #     # Install Azure CLI
    #     curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    #     # Deploy the versioned Docker image
    #     echo "🚀 Deploying Docker image: $DockerImageName"
    #     az login --service-principal -u $AzureAppID -p $AzureAPIKey --tenant $AzureTenantID
    #     az webapp config container set --name $AzureWebAppNameProd --resource-group $AzureResourceGroupNameProd --docker-custom-image-name $DockerImageName

    #     echo "✅ Deployed to Azure Web App: $AzureWebAppNameProd"
