name: 'publish-katalon-report'
description: 'Publish katalon report'
inputs:
  testProjectPath:
    description: "Path to Katalon Project"
    required: false
    default: "./"
  githubToken:
    description: "GitHub token"
    required: false
  repoOrg:
    description: "repo org"
    required: false
    default: "VirtoCommerce"
  publishComment:
    description: "Publish PR Comment"
    required: false
    default: "true"
  publishStatus:
    description: "Publish commit's status"
    required: false
    default: "false"

runs:
  using: 'node12'
  main: 'dist/index.js'