name: 'publish-katalon-report'
description: 'Publish katalon report'
inputs:
  testProjectPath:
    description: "Path to Katalon Project"
    required: false
    default: "./"
  githubToken:
    description: "GitHub token"
    required: true
  repoOrg:
    description: "repo org"
    required: false
    default: "VirtoCommerce"

runs:
  using: 'node12'
  main: 'dist/index.js'