name: 'Docker Environment'
description: 'Runs Docker Environment'
inputs:
  githubUser:
    description: 'User for github packages'
    required: true
  githubToken:
    description: 'Token for github packages'
    required: true
  dockerTag:
    description: 'Docker tag'
    required: false
  platformDockerTag:
    description: 'Platform Docker Tag'
    required: false
    default: 'dev-linux-latest'
  storefrontDockerTag:
    description: 'Storefront Docker Tag'
    required: false
    default: 'dev-linux-latest'
  platformImage:
    description: 'Platform Docker Image'
    required: false
  storefrontImage:
    description: 'Storefront Docker Image'
    required: false
  validateSwagger:
    description: 'Enable or disable swagger validation'
    required: false
    default: 'true'
  installModule:
    description: 'Boolean param. true - to install'
    required: false
    default: ''
  moduleId:
    description: 'Module id'
    required: false
  installModules:
    description: 'Enable or disable "Install Modules" step'
    required: false
    default: 'true'
  installSampleData:
    description: 'Enable or disable "Install Sample Data" step'
    required: true
    default: 'true'

runs:
  using: "composite"
  steps:

    - name: Install VirtoCommerce.GlobalTool
      shell: pwsh
      run: dotnet tool install --global VirtoCommerce.GlobalTool --version 2.0.0-alpha.36

    - name: Install Modules
      working-directory: ${{ github.action_path }}
      shell: pwsh
      run: |
        if("${{ inputs.installModules }}" -eq "true")
        {
          Write-Host "Install Modules step started"
          New-Item -Path "./" -Name "modules" -ItemType "directory"
          Push-Location ./modules
          vc-build install -skip InstallPlatform
          Pop-Location
        }

    - name: Start containers
      env:
        PLATFORM_IMAGE: ${{ inputs.platformImage }}
        STOREFRONT_IMAGE: ${{ inputs.storefrontImage }}
        PLATFORM_DOCKER_TAG: ${{ inputs.platformDockerTag }}
        STOREFRONT_DOCKER_TAG: ${{ inputs.storefrontDockerTag }}
      shell: pwsh
      working-directory: ${{ github.action_path }}
      run: |
        docker-compose --project-name virtocommerce up -d 

    - name: Check Installed Modules
      working-directory: ${{ github.action_path }}
      shell: pwsh
      run: |
        if("${{ inputs.installModules }}" -eq "true")
        {
          Write-Host "Check Installed Modules step started"
          $platformContainer = "virtocommerce_vc-platform-web_1"
          scripts/check-installed-modules.ps1 -ApiUrl http://localhost:8090 -ContainerId $platformContainer -Verbose -Debug
        }

    - name: Install Sample Data
      working-directory: ${{ github.action_path }}
      shell: pwsh
      run: |
        if("${{ inputs.installSampleData }}" -ne "true")
        {
          exit 0
        }
        Write-Host "Install Sample Data step started"
        scripts/setup-sampledata.ps1 -ApiUrl http://localhost:8090 -Verbose -Debug


    - name: Swagger Schema Validation
      shell: pwsh
      run: |
        if("${{ inputs.validateSwagger }}" -ne "true")
        {
          exit 0
        }
        docker pull swaggerapi/swagger-validator-v2
        docker run -d -p 85:8080 swaggerapi/swagger-validator-v2
        Start-Sleep -Seconds 30
        ${{ github.action_path }}/scripts/get-swagger.ps1 -ApiUrl http://localhost:8090 -OutFile ${{ github.action_path }}/swaggerSchema.json -Verbose -Debug
        Get-ChildItem
        Get-ChildItem ${{ github.action_path }}
        Get-Content -Path ${{ github.action_path }}/swaggerSchema.json -TotalCount 10
        vc-build ValidateSwaggerSchema -SwaggerSchemaPath ${{ github.action_path }}/swaggerSchema.json -SwaggerValidatorUri http://localhost:85/validator/debug
