name: 'Docker Environment'
description: 'Runs Docker Environment'
inputs:
  githubUser:
    description: 'User for github packages'
    required: true
  githubToken:
    description: 'Token for github packages'
    required: true
  dockerTag:
    description: 'Docker tag'
    required: false
  platformDockerTag:
    description: 'Platform Docker Tag'
    required: false
    default: 'dev-linux-latest'
  storefrontDockerTag:
    description: 'Storefront Docker Tag'
    required: false
    default: 'dev-linux-latest'
  platformImage:
    description: 'Platform Docker Image'
    required: false
  storefrontImage:
    description: 'Storefront Docker Image'
    required: false
  validateSwagger:
    description: 'Enable or disable swagger validation'
    required: false
    default: 'true'
  installModule:
    description: 'Boolean param. true - to install'
    required: false
    default: ''
  moduleId:
    description: 'Module id'
    required: false

runs:
  using: "composite"
  steps:
    - name: Start containers
      env:
        PLATFORM_IMAGE: ${{ inputs.platformImage }}
        STOREFRONT_IMAGE: ${{ inputs.storefrontImage }}
        PLATFORM_DOCKER_TAG: ${{ inputs.platformDockerTag }}
        STOREFRONT_DOCKER_TAG: ${{ inputs.storefrontDockerTag }}
      shell: pwsh
      working-directory: ${{ github.action_path }}
      run: |
        docker-compose --project-name virtocommerce up -d 

    - name: Install Modules
      working-directory: ${{ github.action_path }}
      shell: pwsh
      run: |
        $platformContainer = "virtocommerce_vc-platform-web_1"
        scripts/setup-modules.ps1 -ApiUrl http://localhost:8090 -NeedRestart -ContainerId $platformContainer -Verbose -Debug
        
        if("${{ inputs.installModule }}" -eq "true")
        {
          $workspace = $env:GITHUB_WORKSPACE
          Write-Output "Workspace: $workspace"
          $artifacts = Get-ChildItem "$($workspace)/artifacts/*.zip"
          $moduleArtifactPath = "$($workspace)/artifacts/$($artifacts[0].Name)"
          $moduleDir = "${{ inputs.moduleId }}"
          Write-Output $moduleDir
          docker ps -a
          Expand-Archive -Path $moduleArtifactPath -DestinationPath ./$($moduleDir)
          $containerDest = "/opt/virtocommerce/platform/Modules"
          Write-Output "Remove previous module version"
          docker exec $platformContainer sh -c "rm -rf ${containerDest}/${moduleDir}"
          docker cp ${moduleDir}/. ${platformContainer}:${containerDest}
          Write-Output "Start Restart: $($platformContainer)"
          docker restart $platformContainer
        }
        scripts/check-installed-modules.ps1 -ApiUrl http://localhost:8090 -Verbose -Debug
        
    - name: Install Sample Data
      working-directory: ${{ github.action_path }}
      shell: pwsh
      run: scripts/setup-sampledata.ps1 -ApiUrl http://localhost:8090 -Verbose -Debug

    - name: Swagger Schema Validation
      shell: pwsh
      run: |
        if("${{ inputs.validateSwagger }}" -ne "true")
        {
          exit 0
        }
        ${{ github.action_path }}/scripts/get-swagger.ps1 -ApiUrl http://localhost:8090 -OutFile ${{ github.action_path }}/swaggerSchema.json -Verbose -Debug
        Get-ChildItem
        Get-ChildItem ${{ github.action_path }}
        vc-build ValidateSwaggerSchema -SwaggerSchemaPath ${{ github.action_path }}/swaggerSchema.json -SwaggerValidatorUri https://validator.swagger.io/validator/debug
