name: 'Docker Environment'
description: 'Runs Docker Environment'
inputs:
  githubUser:
    description: 'User for github packages'
    required: true
  githubToken:
    description: 'Token for github packages'
    required: true
  dockerTag:
    description: 'Docker tag'
    required: false
  platformDockerTag:
    description: 'Platform Docker Tag'
    required: false
    default: 'dev-linux-latest'
  storefrontDockerTag:
    description: 'Storefront Docker Tag'
    required: false
    default: 'dev-linux-latest'
  platformImage:
    description: 'Platform Docker Image'
    required: false
  storefrontImage:
    description: 'Storefront Docker Image'
    required: false
  validateSwagger:
    description: 'Enable or disable swagger validation'
    required: false
    default: 'true'
  installCustomModule:
    description: 'Boolean param. true - to install custom module ver.'
    required: false
    default: 'false'
  customModuleId:
    description: 'Custom Module id'
    required: false
    default: ''
  customModuleUrl:
    description: 'Custom module Module url'
    required: false
    default: ''
  installModules:
    description: 'Enable or disable "Install Modules" step'
    required: false
    default: 'true'
  installSampleData:
    description: 'Enable or disable "Install Sample Data" step'
    required: true
    default: 'true'

runs:
  using: "composite"
  steps:

    - name: Install Modules
      working-directory: ${{ github.action_path }}
      shell: pwsh
      run: |
        if("${{ inputs.installModules }}" -eq "true")
        {
          Write-Host "`e[33mInstall Modules step started."
          New-Item -Path "./" -Name "modules" -ItemType "directory"
          Push-Location ./modules
          vc-build install -skip InstallPlatform
          Pop-Location

          Write-Host "`e[32mModules installed."
        }
        if("${{ inputs.installCustomModule }}" -eq "true")
        {
          Write-Host "`e[33mInstall Custom Modules step started."
          $customModuleZip = "./${{ inputs.customModuleId }}.zip"
          Push-Location ./modules
          Write-Host "`e[33mUninstall ${{ inputs.customModuleId }}."
          vc-build uninstall -module ${inputs.moduleId}
          Write-Host "`e[33mDownload ${{ inputs.customModuleUrl}}to $($customModuleZip)."
          Invoke-WebRequest -Uri ${{ inputs.customModuleUrl}} -OutFile $customModuleZip
          Write-Host "`e[33mExpantd $($customModuleZip) from zip."
          Expand-Archive $customModuleZip -Force
          Write-Host "`e[33mDelete $($customModuleZip)."
          Remove-Item -Path $customModuleZip
          Pop-Location
        }

    - name: Start containers
      env:
        PLATFORM_IMAGE: ${{ inputs.platformImage }}
        STOREFRONT_IMAGE: ${{ inputs.storefrontImage }}
        PLATFORM_DOCKER_TAG: ${{ inputs.platformDockerTag }}
        STOREFRONT_DOCKER_TAG: ${{ inputs.storefrontDockerTag }}
      shell: pwsh
      working-directory: ${{ github.action_path }}
      run: |
        Write-Host "`e[33mStart Containers step started."
        $platformContainer = "virtocommerce_vc-platform-web_1"
        . "./scripts/inspect-docker-status.ps1"

        docker-compose --project-name virtocommerce up -d

        InspectContainerStatus -ContainerId $platformContainer
        
        Write-Host "`e[32mContainers started."

    - name: Check Installed Modules
      working-directory: ${{ github.action_path }}
      shell: pwsh
      run: |
        if("${{ inputs.installModules }}" -eq "true")
        {

          Write-Host "`e[33mCheck Installed Modules step started."
          $platformContainer = "virtocommerce_vc-platform-web_1"
          scripts/check-installed-modules.ps1 -ApiUrl http://localhost:8090 -ContainerId $platformContainer
          Write-Host "`e[32mInstalled Modules checked."
        }

    - name: Install Sample Data
      working-directory: ${{ github.action_path }}
      shell: pwsh
      run: |
        if("${{ inputs.installSampleData }}" -ne "true")
        {
          exit 0
        }

        Write-Host "`e[33mInstall Sample Data step started."
        scripts/setup-sampledata.ps1 -ApiUrl http://localhost:8090 -Verbose -Debug
        Write-Host "`e[32mSample Data installed."

    - name: Swagger Schema Validation
      shell: pwsh
      run: |
        if("${{ inputs.validateSwagger }}" -ne "true")
        {
          exit 0
        }
        $waitForSwaggerSec = 30
        Write-Host "`e[33mSwagger Schema Validation step started."
        $platformContainer = "virtocommerce_vc-platform-web_1"
        . "${{ github.action_path }}/scripts/watch-url-up.ps1"
        $platformIsUp = (Watch-Url-Up -ApiUrl http://localhost:8090 -TimeoutMinutes 15 -RetrySeconds 15 -WaitSeconds 0 -ContainerId $platformContainer)
        if ($platformIsUp) {
          docker pull swaggerapi/swagger-validator-v2
          docker run -d -p 85:8080 swaggerapi/swagger-validator-v2
          Write-Host "`e[33mWait before swagger-validator-v2 start for $waitForSwaggerSec seconds."
          Start-Sleep -Seconds $waitForSwaggerSec
          ${{ github.action_path }}/scripts/get-swagger.ps1 -ApiUrl http://localhost:8090 -OutFile ${{ github.action_path }}/swaggerSchema.json -Verbose -Debug
          Get-ChildItem
          Get-ChildItem ${{ github.action_path }}
          Get-Content -Path ${{ github.action_path }}/swaggerSchema.json -TotalCount 10
          vc-build ValidateSwaggerSchema -SwaggerSchemaPath ${{ github.action_path }}/swaggerSchema.json -SwaggerValidatorUri http://localhost:85/validator/debug
        }
        Write-Host "`e[32mSwagger Schema validated."
