name: 'Docker Environment'
description: 'Runs Docker Environment'
inputs:
  githubUser:
    description: 'User for github packages'
    required: true
  githubToken:
    description: 'Token for github packages'
    required: true
  dockerTag:
    description: 'Docker tag'
    required: false
  platformDockerTag:
    description: 'Platform Docker Tag'
    required: false
    default: 'dev-linux-latest'
  storefrontDockerTag:
    description: 'Storefront Docker Tag'
    required: false
    default: 'dev-linux-latest'
  platformImage:
    description: 'Platform Docker Image'
    required: false
  storefrontImage:
    description: 'Storefront Docker Image'
    required: false
  validateSwagger:
    description: 'Enable or disable swagger validation'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Start containers
      env:
        PLATFORM_IMAGE: ${{ inputs.platformImage }}
        STOREFRONT_IMAGE: ${{ inputs.storefrontImage }}
        PLATFORM_DOCKER_TAG: ${{ inputs.platformDockerTag }}
        STOREFRONT_DOCKER_TAG: ${{ inputs.storefrontDockerTag }}
      shell: pwsh
      working-directory: ${{ github.action_path }}
      run: |
        docker-compose --project-name virtocommerce up -d 

    - name: Install Modules
      working-directory: ${{ github.action_path }}
      shell: pwsh
      run: |
        scripts/setup-modules.ps1 -ApiUrl http://localhost:8090 -NeedRestart -ContainerId virtocommerce_vc-platform-web_1 -Verbose -Debug
        scripts/check-installed-modules.ps1 -ApiUrl http://localhost:8090 -Verbose -Debug

    - name: Install Sample Data
      working-directory: ${{ github.action_path }}
      shell: pwsh
      run: scripts/setup-sampledata.ps1 -ApiUrl http://localhost:8090 -Verbose -Debug

    - name: Swagger Schema Validation
      shell: pwsh
      run: |
        if("${{ inputs.validateSwagger }}" -ne "true")
        {
          exit 0
        }
        ${{ github.action_path }}/scripts/get-swagger.ps1 -ApiUrl http://localhost:8090 -OutFile ${{ github.action_path }}/swaggerSchema.json -Verbose -Debug
        Get-ChildItem
        Get-ChildItem ${{ github.action_path }}
        vc-build ValidateSwaggerSchema -SwaggerSchemaPath ${{ github.action_path }}/swaggerSchema.json -SwaggerValidatorUri https://validator.swagger.io/validator/debug
