name: 'docker-install-modules'
description: 'Installs modules to a docker container'
inputs:
  manifestUrl:
    description: 'Url to modules manifest '
    required: true
  manifestFormat:
    description: 'yml or json'
    required: true
  modulesGroup:
    description: 'Group f modules (commerce for example)'
    required: false
  containerName:
    description: 'Name of docker container'
    required: true
  containerDestination:
    description: 'Theme destination path inside the docker container'
    required: true
  restartContainer:
    description: 'true(by default) to restart'
    required: false
    default: 'true'
runs:
  using: 'node12'
  main: 'dist/index.js' 