name: 'publish-github-release'
description: 'Publish github release or prerelease dependant to github.ref'
inputs:
  changelog:
    description: "Commit's messages since the latest release"
    default: ""
    required: false
  prerelease:
    description: ""
    default: "false"
    required: false
  organization:
    description: "Organization name"
    default: "VirtoCommerce"
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'