name: 'publish-github-release'
description: 'Publish github release or prerelease dependant to github.ref'
inputs:
  changelog:
    description: "Commit's messages since the latest release"
    required: true
outputs:
  blobUrl:
    description: There will be a blob url in case of prerelease
runs:
  using: 'node12'
  main: 'index.js'