name: 'publish-github-release'
description: 'Publish github release or prerelease dependant to github.ref'
inputs:
  changelog:
    description: "Commit's messages since the latest release"
    required: true
  modulesJsonUrl:
    description: "Url to modules.json"
    default: "https://raw.githubusercontent.com/VirtoCommerce/vc-modules/master/modules_v3.json"
    required: false
  blobUrl:
    description: "Url to Azure Blob"
    default: "https://vc3prerelease.blob.core.windows.net/packages"
    required: false
outputs:
  blobUrl:
    description: There will be a blob url in case of prerelease
runs:
  using: 'node12'
  main: 'index.js'