name: 'publish-theme'
description: 'Publishes Theme to Azure blob or Github Release'
inputs:
  release_branch: 
    description: 'Branche support preparation of a new production release'
    required: false
    default: "master"
  artifactPath:
    description: 'Path to artifact'
    required: false
  artifactName:
    description: 'Name of artifact'
    required: false
  blobUrl:
    description: 'Blob Url'
    required: false
    default: 'https://vc3prerelease.blob.core.windows.net/packages'
outputs:
  blobUrl:
    description: 'URL to artifact'
  artifactPath:
    description: 'Path to artifact'
  artifactName:
    description: 'Name of artifact'

runs:
  using: 'node12'
  main: 'index.js'