name: 'get-jira-keys'
description: 'Find issue keys inside event commits'
outputs:
  jira-keys:
    description: 'Jira keys that were found in push/pull request in comma delimited format'
runs:
  using: 'node12'
  main: 'dist/index.js' 