name: 'Update docs.virtocommerce.org (Versioned)'
description: 'Makes and updates versioned documentation for docs.virtocommerce.org using Mike'
inputs:
  githubToken:
    description: "GitHub token with push permissions to gh-pages branch"
    required: true
  version:
    description: "Documentation version to deploy for ALL subsites (e.g., 3.2025-S13, 1.0). Leave empty to use individual versions."
    required: false
  setAsLatest:
    description: "Set this version as 'latest' alias"
    required: false
    default: 'true'
  setAsDefault:
    description: "Set this version as default version"
    required: false
    default: 'false'
  # Individual subsite versions (optional, override global version)
  marketplaceDeveloperGuideVersion:
    description: "Version for marketplace/developer-guide (overrides global version)"
    required: false
  marketplaceUserGuideVersion:
    description: "Version for marketplace/user-guide (overrides global version)"
    required: false
  platformDeveloperGuideVersion:
    description: "Version for platform/developer-guide (overrides global version)"
    required: false
  platformUserGuideVersion:
    description: "Version for platform/user-guide (overrides global version)"
    required: false
  platformDeploymentOnCloudVersion:
    description: "Version for platform/deployment-on-cloud (overrides global version)"
    required: false
  storefrontDeveloperGuideVersion:
    description: "Version for storefront/developer-guide (overrides global version)"
    required: false
  storefrontUserGuideVersion:
    description: "Version for storefront/user-guide (overrides global version)"
    required: false
  azureSubscriptionId:
    description: "Azure Subscription ID"
    required: true
  azureResourceGroupName:
    description: "Azure Resource Group Name"
    required: true
  azureWebAppName:
    description: "Azure WebApp Name"
    required: true
  azureTenantId:
    description: "Azure Tenant ID"
    required: true
  azureApiKey:
    description: "Azure API Key"
    required: true
  azureAppId:
    description: "Azure App ID"
    required: true
  dockerRegistry:
    description: "Docker Registry"
    required: true
  dockerUsr:
    description: "Docker User"
    required: true
  dockerPwd:
    description: "Docker Password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout vc-docs repository
      uses: actions/checkout@v3
      with:
        repository: VirtoCommerce/vc-docs
        ref: feat/custom_versioning
        path: vc-docs
        fetch-depth: 0  # Need full history for gh-pages branch
        token: ${{ inputs.githubToken }}
        persist-credentials: true

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install MkDocs and Mike
      shell: bash
      run: |
        pip install mkdocs-material mike
        pip install mkdocs-awesome-pages-plugin mkdocs-git-revision-date-localized-plugin
        pip install mkdocs-minify-plugin mkdocs-redirects mkdocs-monorepo-plugin
        pip install mkdocs-include-markdown-plugin pymdown-extensions jinja2

    - name: Configure Git
      shell: bash
      working-directory: ${{ github.workspace }}/vc-docs
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Build and deploy versioned documentation
      shell: bash
      working-directory: ${{ github.workspace }}/vc-docs
      run: |
        # Map subsites to their versions
        declare -A SUBSITE_VERSIONS
        
        GLOBAL_VERSION="${{ inputs.version }}"
        SET_LATEST="${{ inputs.setAsLatest }}"
        SET_DEFAULT="${{ inputs.setAsDefault }}"
        
        # Set individual versions or use global version
        SUBSITE_VERSIONS["marketplace/developer-guide"]="${{ inputs.marketplaceDeveloperGuideVersion }}"
        SUBSITE_VERSIONS["marketplace/user-guide"]="${{ inputs.marketplaceUserGuideVersion }}"
        SUBSITE_VERSIONS["platform/developer-guide"]="${{ inputs.platformDeveloperGuideVersion }}"
        SUBSITE_VERSIONS["platform/user-guide"]="${{ inputs.platformUserGuideVersion }}"
        SUBSITE_VERSIONS["platform/deployment-on-cloud"]="${{ inputs.platformDeploymentOnCloudVersion }}"
        SUBSITE_VERSIONS["storefront/developer-guide"]="${{ inputs.storefrontDeveloperGuideVersion }}"
        SUBSITE_VERSIONS["storefront/user-guide"]="${{ inputs.storefrontUserGuideVersion }}"
        
        echo "Deploying versioned documentation..."
        echo "Global version: ${GLOBAL_VERSION:-'not set'}"
        echo "Set as latest: $SET_LATEST"
        echo "Set as default: $SET_DEFAULT"
        echo ""
        
        # Deploy each subsite
        for SUBSITE in "marketplace/developer-guide" "marketplace/user-guide" "platform/developer-guide" "platform/user-guide" "platform/deployment-on-cloud" "storefront/developer-guide" "storefront/user-guide"; do
          # Get version for this subsite (individual or global)
          SUBSITE_VERSION="${SUBSITE_VERSIONS[$SUBSITE]}"
          if [ -z "$SUBSITE_VERSION" ]; then
            SUBSITE_VERSION="$GLOBAL_VERSION"
          fi
          
          # Skip if no version specified
          if [ -z "$SUBSITE_VERSION" ]; then
            echo "⊘ Skipping $SUBSITE (no version specified)"
            echo ""
            continue
          fi
          
          echo "→ Deploying $SUBSITE (version: $SUBSITE_VERSION)..."
          
          CONFIG="$SUBSITE/mkdocs.yml"
          
          # Build mike command
          MIKE_ARGS=("deploy" "-F" "$CONFIG" "--deploy-prefix" "$SUBSITE" "--update-aliases" "$SUBSITE_VERSION")
          
          # Add latest alias if requested
          if [ "$SET_LATEST" == "true" ]; then
            MIKE_ARGS+=("latest")
          fi
          
          # Add push flag to automatically push to gh-pages
          MIKE_ARGS+=("--push")
          
          # Execute mike deploy
          mike "${MIKE_ARGS[@]}"
          
          # Set as default if requested
          if [ "$SET_DEFAULT" == "true" ]; then
            echo "  Setting as default..."
            mike set-default -F "$CONFIG" --deploy-prefix "$SUBSITE" "$SUBSITE_VERSION" --push
          fi
          
          echo "  ✓ Done"
          echo ""
        done
        
        echo "✓ Deployment completed!"
        echo "Changes pushed to gh-pages branch"

    - name: Export versioned documentation from gh-pages
      shell: bash
      working-directory: ${{ github.workspace }}/vc-docs
      run: |
        # Switch to gh-pages branch
        git checkout gh-pages
        
        # Copy all versioned content to site directory
        mkdir -p ../site
        cp -r . ../site/
        
        # Switch back to main branch
        git checkout -

    - name: Build non-versioned root and intermediate sites
      shell: bash
      working-directory: ${{ github.workspace }}/vc-docs
      run: |
        # Build root site
        mkdocs build -d ../site-temp
        
        # Copy root site files (not overwriting versioned subsites)
        cp -n ../site-temp/* ../site/ || true
        cp -rn ../site-temp/assets ../site/ || true
        
        # Build intermediate sites
        mkdocs build -f storefront/mkdocs.yml -d ../site-temp/storefront
        mkdocs build -f platform/mkdocs.yml -d ../site-temp/platform
        mkdocs build -f marketplace/mkdocs.yml -d ../site-temp/marketplace
        
        # Copy intermediate sites (not overwriting versioned subsites)
        cp -rn ../site-temp/storefront/* ../site/storefront/ || true
        cp -rn ../site-temp/platform/* ../site/platform/ || true
        cp -rn ../site-temp/marketplace/* ../site/marketplace/ || true

    - name: Prepare Docker context
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        # Copy site directory for Docker
        cp -r site vc-docs/
        
        # Copy Docker files
        cp -r ${{ github.action_path }}/docker/* ./

    - name: Build and Push Docker image
      shell: pwsh
      working-directory: ${{ github.workspace }}
      run: |
        dotnet tool install --global VirtoCommerce.GlobalTool
        vc-build BuildAndPush `
          -DockerUsername ${{ inputs.dockerUsr }} `
          -DockerPassword ${{ inputs.dockerPwd }} `
          -DockerfilePath ./Dockerfile `
          -DockerImageName ${{ inputs.dockerRegistry }}/vcpt/docs-versioned `
          -DockerImageTag ${{ inputs.version }} `
          -DockerRegistryUrl ${{ inputs.dockerRegistry }}

