name: 'Update docs.virtocommerce.org (Versioned)'
description: 'Makes and updates versioned documentation for docs.virtocommerce.org using Mike'
outputs:
  docker-image-tag:
    description: "Docker image tag that was used for the build"
    value: ${{ steps.docker-tag.outputs.tag }}
inputs:
  githubToken:
    description: "GitHub token with push permissions to gh-pages branch"
    required: true
  version:
    description: "Documentation version to deploy for ALL subsites (e.g., 3.2025-S13, 1.0). Leave empty to use individual versions."
    required: false
  setAsLatest:
    description: "Set this version as 'latest' alias"
    required: false
    default: 'true'
  setAsDefault:
    description: "Set this version as default version"
    required: false
    default: 'false'
  # Individual subsite versions (optional, override global version)
  marketplaceDeveloperGuideVersion:
    description: "Version for marketplace/developer-guide (overrides global version)"
    required: false
  marketplaceUserGuideVersion:
    description: "Version for marketplace/user-guide (overrides global version)"
    required: false
  platformDeveloperGuideVersion:
    description: "Version for platform/developer-guide (overrides global version)"
    required: false
  platformUserGuideVersion:
    description: "Version for platform/user-guide (overrides global version)"
    required: false
  platformDeploymentOnCloudVersion:
    description: "Version for platform/deployment-on-cloud (overrides global version)"
    required: false
  storefrontDeveloperGuideVersion:
    description: "Version for storefront/developer-guide (overrides global version)"
    required: false
  storefrontUserGuideVersion:
    description: "Version for storefront/user-guide (overrides global version)"
    required: false
  azureSubscriptionId:
    description: "Azure Subscription ID"
    required: true
  azureResourceGroupName:
    description: "Azure Resource Group Name"
    required: true
  azureWebAppName:
    description: "Azure WebApp Name"
    required: true
  azureTenantId:
    description: "Azure Tenant ID"
    required: true
  azureApiKey:
    description: "Azure API Key"
    required: true
  azureAppId:
    description: "Azure App ID"
    required: true
  dockerRegistry:
    description: "Docker Registry"
    required: true
  dockerUsr:
    description: "Docker User"
    required: true
  dockerPwd:
    description: "Docker Password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout vc-docs repository
      uses: actions/checkout@v3
      with:
        repository: VirtoCommerce/vc-docs
        ref: feat/custom_versioning
        path: vc-docs
        fetch-depth: 0  # Need full history for gh-pages branch
        token: ${{ inputs.githubToken }}
        persist-credentials: true

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install MkDocs and Mike
      shell: bash
      run: |
        pip install mkdocs-material mike
        pip install mkdocs-awesome-pages-plugin mkdocs-git-revision-date-localized-plugin
        pip install mkdocs-minify-plugin mkdocs-redirects mkdocs-monorepo-plugin
        pip install mkdocs-include-markdown-plugin pymdown-extensions jinja2

    - name: Configure Git
      shell: bash
      working-directory: ${{ github.workspace }}/vc-docs
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Build and deploy versioned documentation
      shell: bash
      working-directory: ${{ github.workspace }}/vc-docs
      run: |
        # Map subsites to their versions
        declare -A SUBSITE_VERSIONS
        
        GLOBAL_VERSION="${{ inputs.version }}"
        SET_LATEST="${{ inputs.setAsLatest }}"
        SET_DEFAULT="${{ inputs.setAsDefault }}"
        
        # Set individual versions or use global version
        SUBSITE_VERSIONS["marketplace/developer-guide"]="${{ inputs.marketplaceDeveloperGuideVersion }}"
        SUBSITE_VERSIONS["marketplace/user-guide"]="${{ inputs.marketplaceUserGuideVersion }}"
        SUBSITE_VERSIONS["platform/developer-guide"]="${{ inputs.platformDeveloperGuideVersion }}"
        SUBSITE_VERSIONS["platform/user-guide"]="${{ inputs.platformUserGuideVersion }}"
        SUBSITE_VERSIONS["platform/deployment-on-cloud"]="${{ inputs.platformDeploymentOnCloudVersion }}"
        SUBSITE_VERSIONS["storefront/developer-guide"]="${{ inputs.storefrontDeveloperGuideVersion }}"
        SUBSITE_VERSIONS["storefront/user-guide"]="${{ inputs.storefrontUserGuideVersion }}"
        
        echo "Deploying versioned documentation..."
        echo "Global version: ${GLOBAL_VERSION:-'not set'}"
        echo "Set as latest: $SET_LATEST"
        echo "Set as default: $SET_DEFAULT"
        echo ""
        
        # Deploy each subsite
        for SUBSITE in "marketplace/developer-guide" "marketplace/user-guide" "platform/developer-guide" "platform/user-guide" "platform/deployment-on-cloud" "storefront/developer-guide" "storefront/user-guide"; do
          # Get version for this subsite (individual or global)
          SUBSITE_VERSION="${SUBSITE_VERSIONS[$SUBSITE]}"
          if [ -z "$SUBSITE_VERSION" ]; then
            SUBSITE_VERSION="$GLOBAL_VERSION"
          fi
          
          # Skip if no version specified
          if [ -z "$SUBSITE_VERSION" ]; then
            echo "⊘ Skipping $SUBSITE (no version specified)"
            echo ""
            continue
          fi
          
          echo "→ Deploying $SUBSITE (version: $SUBSITE_VERSION)..."
          
          CONFIG="$SUBSITE/mkdocs.yml"
          
          # Build mike command
          MIKE_ARGS=("deploy" "-F" "$CONFIG" "--deploy-prefix" "$SUBSITE" "--update-aliases" "$SUBSITE_VERSION")
          
          # Add latest alias if requested
          if [ "$SET_LATEST" == "true" ]; then
            MIKE_ARGS+=("latest")
          fi
          
          # Add push flag to automatically push to gh-pages
          MIKE_ARGS+=("--push")
          
          # Execute mike deploy
          mike "${MIKE_ARGS[@]}"
          
          # Set as default if requested
          if [ "$SET_DEFAULT" == "true" ]; then
            echo "  Setting as default..."
            mike set-default -F "$CONFIG" --deploy-prefix "$SUBSITE" "$SUBSITE_VERSION" --push
          fi
          
          echo "  ✓ Done"
          echo ""
        done
        
        echo "✓ Deployment completed!"
        echo "Changes pushed to gh-pages branch"

    - name: Export versioned documentation from gh-pages
      shell: bash
      working-directory: ${{ github.workspace }}/vc-docs
      run: |
        echo "Exporting versioned content from gh-pages branch..."
        
        # Save current branch
        CURRENT_BRANCH=$(git branch --show-current)
        
        # Checkout gh-pages and copy all content
        git checkout gh-pages
        mkdir -p ../site
        # Copy everything including hidden files but excluding .git
        rsync -a --exclude='.git' ./ ../site/
        
        # Return to original branch
        git checkout $CURRENT_BRANCH
        
        echo "✓ Versioned content exported"

    - name: Build non-versioned root and intermediate sites
      shell: bash
      working-directory: ${{ github.workspace }}/vc-docs
      run: |
        echo "Building non-versioned root and intermediate sites..."
        
        # IMPORTANT: Temporarily disable !include directives to avoid building versioned subsites
        # Root mkdocs.yml includes all subsites which would conflict with versioned content
        
        # Create temporary mkdocs.yml for root without subsites
        cat > mkdocs-temp-root.yml << 'EOF'
        INHERIT: mkdocs.yml
        nav:
            - Home: index.md
        EOF
        
        # Build root site without subsites
        mkdocs build -f mkdocs-temp-root.yml -d ../site-root-temp
        
        # Build intermediate sites (they already have subsites commented out in nav)
        mkdocs build -f storefront/mkdocs.yml -d ../site-storefront-temp
        mkdocs build -f platform/mkdocs.yml -d ../site-platform-temp
        mkdocs build -f marketplace/mkdocs.yml -d ../site-marketplace-temp
        
        # Copy root site to main site (versioned content has priority)
        rsync -a --ignore-existing ../site-root-temp/ ../site/
        
        # Copy intermediate sites (versioned subsites have priority)
        mkdir -p ../site/storefront ../site/platform ../site/marketplace
        rsync -a --ignore-existing ../site-storefront-temp/ ../site/storefront/
        rsync -a --ignore-existing ../site-platform-temp/ ../site/platform/
        rsync -a --ignore-existing ../site-marketplace-temp/ ../site/marketplace/
        
        # Cleanup
        rm -f mkdocs-temp-root.yml
        
        echo "✓ Non-versioned sites built and merged"

    - name: Prepare Docker context
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        # Copy versioned site directory for Docker
        cp -r site vc-docs/
        
        # Copy Docker files
        cp -r ${{ github.action_path }}/docker/* ./

    - name: Determine Docker Image Tag
      id: docker-tag
      shell: bash
      run: |
        # Use global version if available, otherwise use run number
        if [ -n "${{ inputs.version }}" ]; then
          TAG="versioned-${{ inputs.version }}"
        else
          TAG="versioned-${{ github.run_number }}"
        fi
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "Docker image tag: $TAG"

    - name: Build and Push Docker image
      shell: pwsh
      working-directory: ${{ github.workspace }}
      run: |
        dotnet tool install --global VirtoCommerce.GlobalTool
        vc-build BuildAndPush `
          -DockerUsername ${{ inputs.dockerUsr }} `
          -DockerPassword ${{ inputs.dockerPwd }} `
          -DockerfilePath ./Dockerfile `
          -DockerImageName ${{ inputs.dockerRegistry }}/vcpt/docs `
          -DockerImageTag ${{ steps.docker-tag.outputs.tag }} `
          -DockerRegistryUrl ${{ inputs.dockerRegistry }}

