name: 'build-theme'
description: 'Builds theme'
inputs:
   releaseBranch: 
    description: "Branch support preparation of a new production release"
    required: false
    default: "master"
   versionSuffix:
    description: "Suffix for prereleases"
    required: true

runs:
  using: 'node12'
  main: 'index.js'