name: 'publish-blob-release'
description: 'Publishes release to Azure Blob'
inputs:
  blobUrl:
    description: "Url to Azure Blob"
    default: "https://vc3prerelease.blob.core.windows.net/packages"
    required: false
  blobSAS:
    description: "Blob SAS"
    required: false
outputs:
  packageUrl:
    description: "Package url"
  blobId:
    description: "Blob id"

runs:
  using: 'node16'
  main: 'dist/index.js' 