name: 'set-version-up'
description: 'Increment version (minor or patch) in Directory.Build.props and [module.manifest]'
inputs:
  githubToken:
    description: 'GitHub Token'
    required: false
  path:
    description: 'Path to directory that contains module.manifest, package.json or Directory.Build.props'
    default: '.'
    required: false
  versionLabel:
    description: 'Accepted values: minor or patch'
    required: true
    default: 'minor'
runs:
  using: 'node16'
  main: 'dist/index.js' 
