name: 'update-deploy-config'
description: 'Creates or updates deployment config in a repository'
inputs:
  gitUserEmail:
    description: 'git config user.email'
    required: false
    default: 'ci@virtocommerce.com'
  gitUserName:
    description: 'git config user.name'
    default: 'vc-ci'
    required: false
  repoName: 
    description: 'Repository where deployment config file should be created/updated'
    required: true
  branchName: 
    description: 'Repository branch where deployment config file should be created/updated'
    required: true
    default: 'dev'
  artifactKey:
    description: 'artifactKey config file value. For example   "artifactKey": "VirtoCommerce.Catalog"'
    required: true
  templatePath:
    description: 'Path where config template file placed'
    required: true
    default: '../templates/argoDeploy.json'
  configPath:
    description: 'Path where config file placed in a `repoName` repository'
    required: true
    default: './argoDeploy.json'

runs:
  using: 'node12'
  main: 'dist/index.js' 