# v1
name: Theme Release alpha CI
on:
  workflow_dispatch:
 

jobs:
  ci:
    runs-on: ubuntu-latest
    env: 
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      BLOB_SAS: ${{ secrets.BLOB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1

    - name: Get Image Version
      uses: VirtoCommerce/vc-github-actions/get-image-version@master
      id: image

    - name: Get changelog
      id: changelog
      uses: VirtoCommerce/vc-github-actions/changelog-generator@master

    - name: SonarCloud Scan
      uses: VirtoCommerce/vc-github-actions/sonar-theme@master

    - name: Build
      uses: VirtoCommerce/vc-github-actions/build-theme@master
      with:
        versionSuffix: ${{ steps.image.outputs.fullSuffix }}

    - name: Publish
      id: publish
      uses: VirtoCommerce/vc-github-actions/publish-theme@master
