name: 'add-version-suffix'
description: 'Adds version suffix in Directory.Build.props and [module.manifest] for prerelease (alpha version)'
inputs:
  versionSuffix:
    description: "Version suffix"
    required: false
    default: ""
runs:
  using: 'node20'
  main: 'index.js'
