name: 'Update blob url in PR'
description: 'Update blob url in PR'
inputs:
  blobUrl:
    description: 'New blob url to update'
    required: true
    type: string
  repo:
    description: 'Repository for PR lookup'
    required: true
    type: string
  branch:
    description: 'Branch for PR lookup'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Update blob url in PR body
      shell: pwsh
      run: |
        # Find PR for the current branch
        $openPrsJson = gh pr list --repo ${{ inputs.repo }} --head ${{ inputs.branch }} --state open --json "number,headRefName,baseRefName"
        $openPrs = $openPrsJson | ConvertFrom-Json
        if (!$openPrs) {
            Write-Host "No open PR for branch ${{ inputs.branch }}"
            exit 0
        }
        $prNumber = $openPrs[0].number

        $prBody = $(gh pr view $prNumber --repo ${{ inputs.repo }} --json body | ConvertFrom-Json).body
        if ($prBody -match 'https:\/\/vc3prerelease.blob.core.windows.net\/packages\/(\S+)') {
            $prUpdatedBody = $prBody.Replace($matches[0], "${{ inputs.blobUrl }}")
            Write-Host "Updated PR body with new blob url: ${{ inputs.blobUrl }}"
        } else {
            Write-Warning "No blob url found in PR body. Skipping update."
            exit 0
        }

        # Update PR body
        gh pr edit $prNumber --repo ${{ inputs.repo }} --body $prUpdatedBody
        if ($lastExitCode -ne 0) {
            Write-Host "Error: Failed to update PR body"
            exit 1
        }
