name: 'Publish Release'
description: 'Publishes Release on Github or Blob'

runs:
  using: "composite"
  steps:
    - name: Get changelog
      id: changelog
      uses: VirtoCommerce/vc-github-actions/changelog-generator@dev
    
    - name: Publish Github Release
      with:
        changelog: ${{ steps.changelog.outputs.changelog }}
      uses: VirtoCommerce/vc-github-actions/publish-github-release@master