name: 'get-deploy-param'
description: 'Get deployment parameters for ArgoCD deployments'
inputs:
  githubToken:
    description: 'GitHub token'
    required: false
  deployConfigPath:
    description: 'Path to the argoDeploy.json'
    required: true
    default: 'argoDeploy.json'
outputs:
  artifactKey:
    description: 'artifactKey value'
  deployAppName:
    description: 'deployAppName value'
  deployRepo: 
    description: 'deployRepo value'
  deployBranchDev:
    description: 'deployBranchDev value'
  deployBranchQa:
    description: 'deployBranchQa value'
  deployBranchProd:
    description: 'deployBranchProd value'
  cmPath:
    description: 'description value'


runs:
  using: 'node12'
  main: 'dist/index.js' 