name: 'Get Image Version'
description: 'This action grabs Version and Version suffix from module.manifest, package.json or Directory.Build.Props file. If Version suffix not present calculate it as a branch commits count'
inputs:
  path:
    description: 'Path to directory that contains module.manifest, package.json or Directory.Build.Props'
    required: false    
outputs:
  branchName:
    description: 'Triggered branch name'
  prefix:
    description: 'Version prefix value'
  suffix:
    description: 'Version suffix value'
  moduleId:
    description: 'Module Id value'
  sha:
    description: 'Version SHA value'
  shortVersion:
    description: 'Version value formatted as prefix-suffix'
  tag:
    description: 'Version value formatted as branchName-prefix-sha'
  fullVersion:
    description: 'Version value formatted as branchName-prefix-suffix'
  taggedVersion:
    description: 'Version value formatted as branchName-prefix-suffix-sha'


runs:
  using: 'node12'
  main: 'index.js'
