name: 'Get Image Tag'
description: 'This action grabs Version and Version suffix from Directory.Build.Props and adds SHA of the current branch or of the head branch of a pull request.'
outputs:
  tag: # id of output
    description: 'Tag value formatted as x.x.x-sha8 or x.x.x-suffix-sha8'
  sha:
    description: 'Full SHA of the current branch or of the head branch of a pull request.'
runs:
  using: 'node12'
  main: 'index.js'
