name: Create webhook for create Jira PR issue Logic App

on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Repo name where webhook should be created
        type: string
        required: true

  
jobs:
  update-webhook:  
    runs-on: ubuntu-latest
    steps:
    - name: Create create Jira issue for contribution PR webhook
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.REPO_TOKEN }}
        script: |
          github.rest.repos.createWebhook({
            owner: "VirtoCommerce",
            repo: "${{ github.event.inputs.repoName }}",
            events: ["pull_request"],
            config: {
              url: "${{secrets.PR_JIRA_ISSUE_LINK}}",
              content_type: "json",
              insecure_ssl: "0"
            }
          })