name: Get pr labels
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11 for dotnet-sonarscanner #Sonar stop accepting Java versions less than 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Set up .net Core 3.1.x for vc-build #GitHib Actions migrates to .net Core 5.x. To vc-build work properly need to manually install .net Core 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Get pr labels
        uses: VirtoCommerce/vc-github-actions/sonar-scanner-begin@PT2023
