name: Get pr labels
on:
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

      - name: Get pr labels
        uses: VirtoCommerce/vc-github-actions/get-pr-labels@PT-2023
