name: test-jira-build

on:
  workflow_dispatch:
  push:
    branches:
      [PT-4258]

jobs:

  push-jira-build:
    runs-on: ubuntu-latest
    env:
      CLOUD_INSTANCE_BASE_URL: ${{secrets.CLOUD_INSTANCE_BASE_URL}}
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      BUILD_STATE: 'successful'
    steps:

    - name: Parse Jira Keys from All Commits
      uses: VirtoCommerce/vc-github-actions/get-jira-keys@PT-4258
      if: always()
      id: jira_keys
      with:
        release: 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}